In [1]:
# import the pandas module for exploratory data analysis
import pandas as pd

In [2]:
# lets try to open the excel file by using pandas read_excel function
''' 
We set the paramter skiprows=1 (it means that we will skip the first row and get the data from row 2 because
we dont need the 1st row data as you can see on the excel file.
'''
df = pd.read_excel("pone.0212445.s004.xlsx", skiprows=1)

In [3]:
# lets try to check the look our data by using head function in pandas that show only first 5 rows
df.head()

,District,Code,Estimate,Prevalence_%,Prevalence_LCL,Prevalence_UCL,NoPLHIV,NoPLHIV_LCL,NoPLHIV_UCL
0,Buffalo City,BUF,Survey,13.600000,10.268000,16.932000,102437,77340,127534
1,Buffalo City,BUF,Fay-Heriott,13.501283,11.031605,16.421802,101693,83092,123691
2,City of Cape Town,CPT,Survey,5.200000,3.044000,7.356000,200751,117517,283985
3,City of Cape Town,CPT,Fay-Heriott,6.020043,4.335072,8.303091,232409,167359,320548
4,West Coast,DC1,Survey,2.700000,0.000000,5.444000,11302,0,22789

In [4]:
# we can also see the last 5 rows by using tail function in pandas
df.tail()

,District,Code,Estimate,Prevalence_%,Prevalence_LCL,Prevalence_UCL,NoPLHIV,NoPLHIV_LCL,NoPLHIV_UCL
99,Mangaung,MAN,Fay-Heriott,9.147425,6.725917,12.325536,101520,74646,136792
100,Nelson Mandela Bay Metro,NMA,Survey,8.300000,3.400000,13.200000,97459,39923,154995
101,Nelson Mandela Bay Metro,NMA,Fay-Heriott,9.054060,6.128703,13.179704,106313,71964,154757
102,City of Tshwane,TSH,Survey,11.700000,7.388000,16.012000,361450,228239,494661
103,City of Tshwane,TSH,Fay-Heriott,11.024858,8.255934,14.574909,340593,255052,450265

### ~What is the total number of people living with HIV (NoPLHIV) in the listed districts according to the Survey estimate?

In [5]:
# lets try to check the dataframe according to the survey
'''
We will extract the data where estimate is equal to survey and store the dataframe in survey_df.
'''
survey_df = df[df['Estimate']=='Survey']

In [6]:
# now we can see that this dataframe is related to survey. All data according to estimates of survey
survey_df

,District,Code,Estimate,Prevalence_%,Prevalence_LCL,Prevalence_UCL,NoPLHIV,NoPLHIV_LCL,NoPLHIV_UCL
0,Buffalo City,BUF,Survey,13.60,10.268000,16.932000,102437,77340,127534
2,City of Cape Town,CPT,Survey,5.20,3.044000,7.356000,200751,117517,283985
4,West Coast,DC1,Survey,2.70,0.000000,5.444000,11302,0,22789
6,Cacadu,DC10,Survey,7.60,3.484000,11.716000,34732,15922,53542
8,Amatole,DC12,Survey,11.00,7.276000,14.724000,98884,65407,132361
10,Chris Hani,DC13,Survey,14.30,10.184000,18.416000,114849,81792,147906
12,Joe Gqabi,DC14,Survey,10.70,7.956000,13.444000,37766,28081,47451
14,O.R. Tambo,DC15,Survey,11.80,8.468000,15.132000,160352,115073,205631
16,Xhariep,DC16,Survey,8.30,6.144000,10.456000,11777,8718,14836
18,Lejweleputswa,DC18,Survey,20.30,13.440000,27.160000,123868,82009,165727
20,Thabo Mofutsanyana,DC19,Survey,15.90,12.960000,18.840000,115006,93741,136271
22,Cape Winelands,DC2,Survey,3.80,0.468000,7.132000,30706,3782,57630
24,Fezile Dabi,DC20,Survey,9.00,6.256000,11.744000,45550,31662,59438
26,Ugu,DC21,Survey,19.50,17.736000,21.264000,142979,130045,155913
28,uMgungundlovu,DC22,Survey,21.00,15.512000,26.488000,221073,163299,278847
30,uThukela,DC23,Survey,17.30,9.460000,25.140000,118124,64593,171655
32,uMzinyathi,DC24,Survey,18.20,16.632000,19.768000,93587,85524,101650
34,Amajuba,DC25,Survey,16.20,13.260000,19.140000,82210,67290,97130
36,Zululand,DC26,Survey,20.80,17.468000,24.132000,171411,143952,198870
38,uMkhanyakude,DC27,Survey,13.50,8.992000,18.008000,86131,57369,114893
40,uThungulu,DC28,Survey,17.30,12.204000,22.396000,162238,114448,210028
42,iLembe,DC29,Survey,12.40,0.640000,24.160000,78178,4035,152321
44,Overberg,DC3,Survey,6.25,0.000000,14.222997,17039,0,38775
46,Gert Sibande,DC30,Survey,19.70,17.936000,21.464000,208067,189436,226698
48,Nkangala,DC31,Survey,9.30,7.340000,11.260000,126270,99658,152882
50,Ehlanzeni,DC32,Survey,16.40,10.324000,22.476000,281104,176959,385249
52,Mopani,DC33,Survey,11.40,5.520000,17.280000,87968,42595,133341
54,Vhembe,DC34,Survey,5.30,0.204000,10.396000,70373,2709,138037
56,Capricorn,DC35,Survey,9.20,4.300000,14.100000,116351,54381,178321
58,Waterberg,DC36,Survey,10.10,7.160000,13.040000,71577,50742,92412
60,Bojanala Platinum,DC37,Survey,13.60,10.856000,16.344000,212904,169947,255861
62,Ngaka Modiri Molema,DC38,Survey,13.80,8.900000,18.700000,117661,75883,159439
64,Dr Ruth Segomotsi Mompati,DC39,Survey,10.90,6.588000,15.212000,51450,31096,71804
66,Eden,DC4,Survey,4.30,1.948000,6.652000,25191,11412,38970
68,Dr Kenneth Kaunda,DC40,Survey,14.50,11.560000,17.440000,102584,81784,123384
70,Sedibeng,DC42,Survey,21.60,12.584000,30.616000,197713,115186,280240
72,Sisonke,DC43,Survey,21.10,13.064000,29.136000,99572,61650,137494
74,Alfred Nzo,DC44,Survey,12.70,6.036000,19.364000,104363,49601,159125
76,John Taolo Gaetsewe,DC45,Survey,8.80,4.096000,13.504000,20323,9460,31186
78,Sekhukhune,DC47,Survey,7.00,3.080000,10.920000,77489,34095,120883
80,West Rand,DC48,Survey,7.10,0.828000,13.372000,60313,7034,113592
82,Central Karoo,DC5,Survey,25.00,9.054006,40.945994,17808,6449,29167
84,Namakwa,DC6,Survey,2.80,0.448000,5.152000,3317,531,6103
86,Pixley ka Seme,DC7,Survey,5.00,3.432000,6.568000,9501,6521,12481
88,Siyanda,DC8,Survey,5.60,3.052000,8.148000,13673,7452,19894
90,Frances Baard,DC9,Survey,12.40,4.952000,19.848000,47040,18786,75294
92,Ekurhuleni,EKU,Survey,14.30,9.792000,18.808000,462059,316397,607721
94,eThekwini,ETH,Survey,14.50,10.776000,18.224000,502310,373303,631317
96,City of Johannesburg,JHB,Survey,11.10,7.964000,14.236000,515387,369778,660996
98,Mangaung,MAN,Survey,7.90,4.764000,11.036000,87676,52872,122480
100,Nelson Mandela Bay Metro,NMA,Survey,8.30,3.400000,13.200000,97459,39923,154995
102,City of Tshwane,TSH,Survey,11.70,7.388000,16.012000,361450,228239,494661

In [7]:
# lets try to check thr total no. of people that living HIV (NoPLHIV) in the listed districts according to the Survey estimate
'''
We will get the column (NoPLHIV) in our survey dataframe and check the len by using len function in python. 
'''
print("Total number of people : ",len(survey_df['NoPLHIV']))

Total number of people :  52

In [8]:
# we can also directly check the counts of each value in estimate by using value_counts function
df['Estimate'].value_counts()

Survey         52
Fay-Heriott    52
Name: Estimate, dtype: int64

### ~What is the average NoPLHIV of the two estimates used for “Xhariep”?

In [9]:
# lets try to extract the data where estimate column is survey or Fay-Heriott and store in survey_df and Fay_Heriott_df variable
survey_df = df[df['Estimate']=='Survey']
Fay_Heriott_df = df[df['Estimate']=='Fay-Heriott']

In [10]:
# Now, we extract the data where District is Xhariep according to survey and store the data into variable s.
s = survey_df[survey_df['District']=='Xhariep']

In [11]:
# lets try to check the average of  NoPLHIV by using mean function and store in avg_s variable
avg_s = s['NoPLHIV'].mean()
print("average NoPLHIV according to estimate(Survey) :",avg_s)

average NoPLHIV according to estimate(Survey) : 11777.0

In [12]:
# Now, we extract the data where District is Xhariep according to Fay_Heriott and store the data into variable f.
f = Fay_Heriott_df[Fay_Heriott_df['District']=='Xhariep']

In [13]:
# lets try to check the average of NoPLHIV by using mean function and store in avg_f variable
avg_f = f['NoPLHIV'].mean()
print("average NoPLHIV according to estimate(Fay_Heriott) :",avg_f)

average NoPLHIV according to estimate(Fay_Heriott) : 12718.0

### ~Add a column and populate it with the number of people not living with HIV for each row.

In [14]:
'''
Now, we create a new column name People and store all the data of people not living with HIV.
We create a list comprehension and iterate all the estimate column value if our estimate values is Survey
then we store the dash and if our estimate value is another then we store the value 'Not Living'.
'''
df['People'] = ['-' if i=='Survey' else 'Not Living' for i in df['Estimate']]

In [15]:
'''Now, we can see that our new column is add in our original dataframe and also we can see that where estimate value is not 
surevy we set the value Not living in People column'''
df.head(20)

,District,Code,Estimate,Prevalence_%,Prevalence_LCL,Prevalence_UCL,NoPLHIV,NoPLHIV_LCL,NoPLHIV_UCL,People
0,Buffalo City,BUF,Survey,13.600000,10.268000,16.932000,102437,77340,127534,-
1,Buffalo City,BUF,Fay-Heriott,13.501283,11.031605,16.421802,101693,83092,123691,Not Living
2,City of Cape Town,CPT,Survey,5.200000,3.044000,7.356000,200751,117517,283985,-
3,City of Cape Town,CPT,Fay-Heriott,6.020043,4.335072,8.303091,232409,167359,320548,Not Living
4,West Coast,DC1,Survey,2.700000,0.000000,5.444000,11302,0,22789,-
5,West Coast,DC1,Fay-Heriott,4.088319,2.414351,6.841548,17114,10107,28639,Not Living
6,Cacadu,DC10,Survey,7.600000,3.484000,11.716000,34732,15922,53542,-
7,Cacadu,DC10,Fay-Heriott,8.912387,6.145010,12.756646,40729,28083,58298,Not Living
8,Amatole,DC12,Survey,11.000000,7.276000,14.724000,98884,65407,132361,-
9,Amatole,DC12,Fay-Heriott,11.878608,9.090702,15.376883,106783,81721,138230,Not Living
10,Chris Hani,DC13,Survey,14.300000,10.184000,18.416000,114849,81792,147906,-
11,Chris Hani,DC13,Fay-Heriott,14.080983,11.181220,17.583893,113090,89801,141224,Not Living
12,Joe Gqabi,DC14,Survey,10.700000,7.956000,13.444000,37766,28081,47451,-
13,Joe Gqabi,DC14,Fay-Heriott,11.507804,9.291766,14.169794,40618,32796,50013,Not Living
14,O.R. Tambo,DC15,Survey,11.800000,8.468000,15.132000,160352,115073,205631,-
15,O.R. Tambo,DC15,Fay-Heriott,12.317316,9.771988,15.412383,167382,132793,209441,Not Living
16,Xhariep,DC16,Survey,8.300000,6.144000,10.456000,11777,8718,14836,-
17,Xhariep,DC16,Fay-Heriott,8.963070,7.187823,11.124214,12718,10199,15784,Not Living
18,Lejweleputswa,DC18,Survey,20.300000,13.440000,27.160000,123868,82009,165727,-
19,Lejweleputswa,DC18,Fay-Heriott,17.628286,13.677049,22.424487,107566,83456,136832,Not Living

### ~What is the total NoPLHIV in all the cities (districts with the word “city” or “metro” in the name)?

In [16]:
'''
Now, we extracting the data where city and metro name is in district column.
we create a comprehension list and iterate all the district and then we convert all the 
district in lower letter and split the words in list by using split function in python and then check the city or 
metro in list that we have split by using split function if exist then store into city or metro variable.
'''
city = [c for c in df['District'] if 'city' in c.lower().split()]
metro = [m for m in df['District'] if 'metro' in m.lower().split()]

In [17]:
# lets try to check the district where city name is exist
city

['Buffalo City',
 'Buffalo City',
 'City of Cape Town',
 'City of Cape Town',
 'City of Johannesburg',
 'City of Johannesburg',
 'City of Tshwane',
 'City of Tshwane']

In [18]:
# lets try to check the total NoPLHIV with the word city
print("total NoPLHIV with the word city in a district :",len(city))

total NoPLHIV with the word city in a district : 8

In [19]:
# lets try to check the district where metro name is exist
metro

['Nelson Mandela Bay Metro', 'Nelson Mandela Bay Metro']

In [20]:
# lets try to check the total NoPLHIV with the word metro
print("total NoPLHIV with the word metro in a district :",len(metro))

total NoPLHIV with the word metro in a district : 2

### ~Write the original data (without the caption - originally row 1) with the extra columns as comma-separated values (CSV) to a new .csv file.

In [21]:
# Now, we store the data into csv by using to_csv function in pandas
df.to_csv("OriginalData.csv")
print("Successfully save data!")

Successfully save data!